apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
  namespace: travelhub-room
  labels:
    app: room-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
      - name: room-service
        image: travelhub/room-service:1.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: HOTEL_SERVICE_URL
          value: "http://hotel-service.travelhub-hotel.svc.cluster.local:8002"
        ports:
        - containerPort: 8003
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8003
          initialDelaySeconds: 2
          periodSeconds: 5
