apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: travelhub
  labels:
    app: travelhub
    component: backend
    service: payment-service
    version: "1.0.5"
    managed-by: kubernetes
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: travelhub
      service: payment-service
  template:
    metadata:
      labels:
        app: travelhub
        component: backend
        service: payment-service
        version: "1.0.5"
        managed-by: kubernetes
    spec:
      containers:
      - name: payment-service
        image: travelhub/payment-service:1.0.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8007
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: PORT
          value: "8007"
