apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: room-service-pdb
  namespace: travelhub
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: travelhub
      service: room-service
