apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: travelhub
  labels:
    app: travelhub
    component: backend
    service: search-service
    version: "1.0.5"
    managed-by: kubernetes
spec:
  type: ClusterIP
  selector:
    app: travelhub
    service: search-service
  ports:
  - port: 8004
    targetPort: 8004
    protocol: TCP
