apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: travelhub
  labels:
    app: travelhub
    component: backend
    service: user-service
    version: "1.0.5"
    managed-by: kubernetes
spec:
  type: ClusterIP
  selector:
    app: travelhub
    service: user-service
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
